### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by DuKerry** [yifeipet/Deep-Learning-for-Block-Level-Compressive-Video-Sensing#1]
您好，看完您的代码，有些地方不理解。想问下您是如何对数据集进行处理的？

**Comment by hopesala** [comment]
container下的数据集文件，不知道怎么来的，网上搜到了个container_cif.y4m，下载下来发现是一种视频格式，直接用这个运行不行，于是想办法转成所需要的yuv格式，不想切换到linux下，在windows10 下搞了个Ubuntu软件，进去sudo apt update然后 sudo apt install ffmpeg，使用命令ffmpeg -i container_cif.y4m ./container1/image%d.jpg先生成了300张图，然后jpg不能用，又使用命令ffmpeg -i container1/image1.jpg container/image1.yuv生成yuv文件，300张太多，写了个python脚本批量处理python3 y4m_to_png.py，脚本内容如下

import os
for i in range(300):
        print('running ', i)
        os.system('ffmpeg -i container1/image'+str(i+1)+'.jpg container/image'+str(i+1)+'.yuv')

**Comment by hopesala** [comment]
@DuKerry

**Comment by yifeipet** [comment]
@DuKerry 抱歉，才看到你的问题。其实这个就是把YUV 文件的Luminance channel给提取出来。@hopesala 说的ffmpeg可以，ffmpeg 在Windows上也能装。但应该有其他的Python库，我当时就是用Python库的。
谢谢。

**Comment by DuKerry** [comment]
非常感谢两位的解答！
